---

- name: get Bannerlord installation path
  set_fact:
    crpg_game_server_local_path: "{{ lookup('env', 'MB_SERVER_PATH') }}"

- name: assert Bannerlord installation path is defined
  assert:
    that: crpg_game_server_local_path | length > 0

- name: check game server files
  stat:
    path: "{{ crpg_game_server_local_path  }}/Modules/cRPG/{{ item }}"
  loop:
    - "DsAssetPackages"
    - "SceneObj"
    - "bin/Win64_Shipping_Server/Crpg.Module.dll"
  register: file_stats
  delegate_to: localhost
  become: false

- name: assert game server files are present
  assert:
    that: item.stat.exists
    fail_msg: "{{ item.item }} was not found"
  loop: "{{ file_stats.results }}"
  delegate_to: localhost
  become: false

- name: compress locally game server
  archive:
    path: "{{ crpg_game_server_local_path }}/Modules/cRPG/*"
    dest: /tmp/crpg-server.zip
    format: zip
  delegate_to: localhost
  become: false

- name: copy game server to host
  copy:
    src: /tmp/crpg-server.zip
    dest: "{{ crpg_ui_path }}/cRPGServer.zip"
    owner: nginx
    group: nginx

- name: copy SubModule.xml server to host
  copy:
    src: "{{ crpg_game_server_local_path  }}/Modules/cRPG/SubModule.xml"
    dest: "{{ crpg_ui_path }}/SubModule.xml"
    owner: nginx
    group: nginx
- name: remove temporary archive
  file:
    path: /tmp/crpg-server.zip
    state: absent
